# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Board Game One-pagers
source: src
destination: dest
host: 0.0.0.0
description: > # this means to ignore newlines until "baseurl:"
  One page instructions for those that have played the game but 
  need to brush up on the rules.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://boardgameonepagers.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  allanhortle

# Build settings
markdown: kramdown
collections:
    rules:
        output: true
        permalink: /:path/

# Default Front-matter
defaults:
  - scope:
      path: ""
      type: rules
    values:
        layout: rule
